version: '3.8'

services:
  bot:
    build: .
    container_name: vpn-bot
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      -
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - /etc/wireguard:/etc/wireguard
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"