version: '3.8'

services:
  bot:
    build: .
    container_name: vpn-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"