name: Deploy VPN Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          if [ ! -d "/root/tg-bot-vpn" ]; then
            cd /root
            git clone https://github.com/inasekin/tg-bot-vpn
          fi
          cd /root/tg-bot-vpn
          git pull origin main
          chmod +x scripts/deploy.sh
          bash scripts/deploy.sh